# STM32 Platform Support
snd-soc-stm32-sai-objs := stm32-sai.o
obj-$(CONFIG_SND_SOC_STM32_SAI) += snd-soc-stm32-sai.o

# STM32 Machine Support
snd-soc-stm32-asoc-card-objs := stm32-asoc-card.o
obj-$(CONFIG_SND_SOC_STM32_ASOC_CARD) += snd-soc-stm32-asoc-card.o
