#ifndef _MACH_STM32_SYSCFG_H_
#define _MACH_STM32_SYSCFG_H_

/*
 * SYSCFG registers bits and masks
 */
#define STM32_SYSCFG_PMC		0x4
#define STM32_SYSCFG_PMC_ETHMODE(x)	((x) << 23)
#define STM32_SYSCFG_PMC_ETHMODE_MASK	STM32_SYSCFG_PMC_ETHMODE(0x3)
#define STM32_SYSCFG_PMC_ETHMODE_MII	STM32_SYSCFG_PMC_ETHMODE(0x0)
#define STM32_SYSCFG_PMC_ETHMODE_RMII	STM32_SYSCFG_PMC_ETHMODE(0x1)

#define STM32_SYSCFG_PMC_ADCxDC2(x)	((x) << 16)
#define STM32_SYSCFG_PMC_ADCxDC2_MASK	STM32_SYSCFG_PMC_ADCxDC2(0x7)

#endif
